### ISSUE TITLE
gomobile broken for go1.20 

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#23]
```
rm -rf /home/mz/x/firestack/build
go clean
mkdir -p /home/mz/x/firestack/build/intra
env PATH=/home/mz/x/firestack/bin:/home/mz/.gvm/pkgsets/go1.20.1/global/bin:/home/mz/.gvm/gos/go1.20.1/bin:/home/mz/.gvm/pkgsets/go1.20.1/global/overlay/bin:/home/mz/.gvm/bin:/home/mz/.gvm/bin:/home/mz/.bun/bin:/home/mz/.age/:/home/mz/.deno/bin:/home/mz/.fly/bin:/home/mz/.nvm/versions/node/v19.0.1/bin:/home/mz/.pyenv/shims:/home/mz/.sdkman/candidates/java/current/bin:/home/mz/.pyenv/shims:/home/mz/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/mz/Android/Sdk/platform-tools:/home/mz/Android/Sdk/tools/bin:/home/mz/go/bin:/home/mz/.yarn/bin /home/mz/x/firestack/bin/gomobile bind -v -a -ldflags '-w -s' -androidapi 23 -target=android -tags='android' -work -o /home/mz/x/firestack/build/intra/tun2socks.aar github.com/celzero/firestack/intra github.com/celzero/firestack/intra/android github.com/celzero/firestack/intra/ipn github.com/celzero/firestack/intra/doh github.com/celzero/firestack/intra/dns53 github.com/celzero/firestack/intra/split github.com/celzero/firestack/intra/protect github.com/celzero/firestack/intra/settings github.com/celzero/firestack/intra/dnscrypt github.com/celzero/firestack/intra/dnsx github.com/celzero/firestack/intra/xdns
unable to import bind/java: [-: # golang.org/x/mobile/bind/java
../../.gvm/pkgsets/go1.20.1/global/pkg/mod/golang.org/x/mobile@v0.0.0-20220518205345-8578da9835fd/bind/java/context_android.go:9:10: fatal error: jni.h: No such file or directory
    9 | //#include <jni.h>
      |          ^~~~~~~
compilation terminated.]
WORK=/tmp/gomobile-work-538333238
/home/mz/x/firestack/bin/gomobile: /home/mz/.gvm/pkgsets/go1.20.1/global/bin/gobind -lang=go,java -outdir=/tmp/gomobile-work-538333238 -tags=android github.com/celzero/firestack/intra github.com/celzero/firestack/intra/android github.com/celzero/firestack/intra/ipn github.com/celzero/firestack/intra/doh github.com/celzero/firestack/intra/dns53 github.com/celzero/firestack/intra/split github.com/celzero/firestack/intra/protect github.com/celzero/firestack/intra/settings github.com/celzero/firestack/intra/dnscrypt github.com/celzero/firestack/intra/dnsx github.com/celzero/firestack/intra/xdns failed: exit status 1

make: *** [Makefile:17: /home/mz/x/firestack/build/intra/tun2socks.aar] Error 1

```

ref: https://github.com/golang/go/issues/58426

**Comment by ignoramous** [comment]
`gomobile` works on go1.21: https://github.com/celzero/firestack/commit/40fb38ea267050cdea485b366b02d11c6f03c900
